codewitgabi/full-featured-social-media-application-fastapi

database.dbml
---
Added database design file for easy collaboration on database schemas
---
- To ease collaboration
​
---
​
---
=> chore: added database.dbml for database design

README.md, database.dbml
---
Update the database.dbml file to meet requirement.
---
---
​
---
=> feat: update database design

.github/workflows/code_test.yaml, .gitignore, api/v1/models/__init__.py, api/v1/models/abstract_base.py, api/v1/models/user.py, main.py
---
https://github.com/codewitgabi/full-featured-social-media-application-fastapi/issues/12
---
- Added user model
- Added database dependency
---
​
---
=> feat: create user model

.github/ISSUE_TEMPLATE/feature_request.md
---
- Added project issue template
---
- To keep sync of changes made to codebase
- For uniformity
---
​
---
=> chore: add feature issue template

alembic/env.py, api/v1/models/__init__.py, api/v1/models/cover_photo.py, api/v1/models/user.py
---
#17
---
- Added cover photo model
- Fix model import
---
- The fix is necessary for models to be inserted into the database.
- New feature `CoverPhoto` model.
​
---
​
---
​
---
=> feat+fix: add cover photo model and update and fix model creation

api/v1/models/__init__.py, api/v1/models/post.py, api/v1/models/user.py
---
#19 
---
- Added `Post` model
---
​
---
​
---
=> feat: add post model

api/v1/models/__init__.py, api/v1/models/access_token.py, api/v1/models/cover_photo.py, api/v1/models/post.py, api/v1/models/user.py
---
#21 
---
- Added `AccessToken` model
---
- `alembic migration`
- `sql table created`
---
​
---
=> feat: add access token model and cleaned up model

api/v1/routes/auth.py, api/v1/schemas/user.py, api/v1/services/user.py, main.py
---
This PR is related to [this issue](https://github.com/codewitgabi/full-featured-social-media-application-fastapi/issues/34)
---
- Endpoint `[POST] /api/v1/auth/logout` was added to logout a user
- AccessToken was blacklisted successfully.
- `user_service.get_current_user` db dependency causing error was fixed by adding the `get_db` to the db session instead of only typing it.
---
- `postman`
​
---
​
---
=> feat: add logout endpoint

README.md, api/v1/routes/user.py, api/v1/services/user.py, api/v1/tests/user/conftest.py, api/v1/tests/user/test_delete_user.py
---
This PR is related to [this issue](#39)
---
---
- `pytest`
```bash
============================= test session starts =============================
platform win32 -- Python 3.10.7, pytest-8.2.2, pluggy-1.5.0 -- C:\Users\HP\OneDrive\Desktop\codes\fast-api-social-media-api\venv\Scripts\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\HP\OneDrive\desktop\Codes\fast-api-social-media-api
plugins: anyio-4.4.0
collecting ... collected 15 items
api/v1/tests/auth/test_user_login.py::test_login_success PASSED          [  6%]
api/v1/tests/auth/test_user_login.py::test_incorrect_email PASSED        [ 13%]
api/v1/tests/auth/test_user_login.py::test_incorrect_password PASSED     [ 20%]
api/v1/tests/auth/test_user_logout.py::test_logout_success PASSED        [ 26%] …
```
=> feat: add endpoint to delete user profile

api/v1/routes/user.py, api/v1/services/user.py, api/v1/tests/user/conftest.py, api/v1/tests/user/test_get_users.py
---
This PR is related to #45
---
- Added endpoint to get list of users randomly
- Implement search to filter users by `username` and `email`
---
- `[GET] http://localhost:5001/api/v1/users`
```json
{
"status_code": 200,
"message": "User list fetched successfully",
"data": [
{
"email": "test-p@example.com",
"contact_info": null,
"last_login": null,
"id": "02bb30ec-c793-463f-a2ea-d83edd156628",
"username": "Test",
"bio": null,
"role": "user",
"updated_at": "2024-08-22T13:03:50.700482+01:00",
"created_at": "2024-08-22T13:03:50.700482+01:00",
"profile_pictures": [],
"social_links": []
},
{
"email": "test-o@example.com",
"contact_info": null,
"last_login": null,
"id": "6dd3ba1e-dbca-482b-95a2-298d59e14981",
"username": "Test",
"bio": null,
"role": "user",
"updated_at": …
```
=> feat: endpoint to fetch all users

api/v1/routes/__init__.py, api/v1/routes/post.py, api/v1/schemas/post.py, api/v1/services/post.py, api/v1/tests/post/conftest.py, api/v1/tests/post/test_create_post.py
---
This PR is related to #48 
---
- Add endpoint to create a new post
- Add tests to cover this endpoint
---
- `[GET] /apii/v1/posts`
```json
{
"status_code": 201,
"message": "Post created successfully",
"data": {
"user_id": "02bb30ec-c793-463f-a2ea-d83edd156628",
"video": null,
"id": "ac3d6659-8f67-4a67-b690-9f77fab7e6e3",
"image": null,
"content": "Lorem ipsum dolor sit amet.",
"updated_at": "2024-08-22T23:59:25.816336+01:00",
"created_at": "2024-08-22T23:59:25.816336+01:00"
}
}
```
​
---
​
---
=> feat: add endpoint to create post

api/v1/routes/post.py, api/v1/schemas/post.py, api/v1/services/post.py, api/v1/tests/post/conftest.py, api/v1/tests/post/test_update_post.py
---
closes #51 
---
This PR adds a new endpoint `[PATCH] /api/v1/posts/{v1}` to the project
---
- pytest
```shell
api/v1/tests/auth/test_user_login.py::test_login_success PASSED                                                            [  4%]
api/v1/tests/auth/test_user_login.py::test_incorrect_email PASSED                                                          [  8%]
api/v1/tests/auth/test_user_login.py::test_incorrect_password PASSED                                                       [ 12%]
api/v1/tests/auth/test_user_logout.py::test_logout_success PASSED                                                          [ 16%]
api/v1/tests/auth/test_user_registration_endpoint.py::test_register_user_success PASSED                                    [ 20%] …
```
=> feat: add update post endpoint

api/v1/routes/post_comment.py, api/v1/services/post_comment.py, api/v1/tests/conftest.py, api/v1/tests/post_comment/conftest.py, api/v1/tests/post_comment/test_get_comments.py
---
#60 
---
Get all comments related to a particular post 
---
​
---
- pytest
​
---
- [] Bug fix (non-breaking change which fixes an issue)
​
---
=> feat: added getting comments endpoint

api/v1/models/post.py, api/v1/models/user.py, api/v1/routes/post.py, api/v1/routes/post_comment.py, api/v1/schemas/post.py, api/v1/services/post.py, api/v1/tests/post/conftest.py, api/v1/tests/post/test_delete_post.py, api/v1/tests/post/test_post_like.py
---
#62 
---
Enables users to react to post
---
​
---
- Pytest
​
---
​
---
=> feat: added like post endpoint

alembic.ini, alembic/env.py, api/v1/models/post.py, api/v1/routes/post.py, api/v1/schemas/post.py, api/v1/schemas/user.py, api/v1/services/post.py, api/v1/tests/post/conftest.py, api/v1/tests/post/test_repost.py
---
#64 
---
Reposting or sharing a post which was posted by current or any other user
---
​
---
- Pytest
​
---
​
---
=> feat: added repost endpoint

api/v1/routes/post.py, api/v1/schemas/post.py, api/v1/services/post.py, api/v1/tests/post/conftest.py, api/v1/tests/post/test_get_feeds.py, api/v1/utils/websocket.py
---
#66
---
Fetching feeds/posts for user using websocket to inject newly created post
---
​
---
- Pytest
- Responses
​
---
​
---
=> feat: added get feeds endpoint

api/v1/models/user.py, api/v1/routes/user.py, api/v1/services/user.py, api/v1/tests/user/conftest.py, api/v1/tests/user/test_follow_user.py
---
#69 
---
Establish friendship by following users 
---
​
---
- Pytest
- 
- Response
- 
​
---
​
---
=> feat: added endpoint for following users 

api/v1/routes/user.py, api/v1/services/user.py, api/v1/tests/user/conftest.py, api/v1/tests/user/test_follow_user.py, api/v1/tests/user/test_followers_followings.py
---
#71 
---
Allow users to see the list of their friends 
---
​
---
​
---
​
---
=> feat: added endpoint for followers and following list

api/v1/services/user.py
---
#73 
---
---
​
---
- pytest
---
​
---
=> feat: added follow and unfollow notification 

api/v1/models/__init__.py, api/v1/models/hashtag.py
---
This PR is related to [this issue](#78)
---
- Added hashtag model
---
​
---
=> feat: added hashtag model
